# Generated by Django 3.0.2 on 2020-01-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(max_length=3)),
                ('desc', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('HID', 'HID 13.56MHz 4kb'), ('Mifare', 'Mifare 13.56MHz 1kb'), ('Unique', 'Unique 125kHZ 1kb')], default='HID', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
