# Generated by Django 3.0.2 on 2020-01-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reader',
            old_name='desc',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='reader',
            name='direction',
            field=models.CharField(choices=[('OUT', 'OUT'), ('IN', 'IN')], max_length=3),
        ),
    ]
