# Generated by Django 3.0.2 on 2020-01-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0003_auto_20200106_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('kind', models.CharField(choices=[('Office', 'Pomieszczenie biurowe'), ('Factory', 'Pomieszczenie produkcyjne'), ('Warehouse', 'Pomieszczenie magazynowe')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
