# Generated by Django 3.0.2 on 2020-01-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0005_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('Office', 'Pomieszczenie biurowe'), ('Factory', 'Pomieszczenie produkcyjne'), ('Warehouse', 'Pomieszczenie magazynowe'), ('Other', 'Inne pomieszczenia')], max_length=10),
        ),
    ]
