# Generated by Django 3.0.2 on 2020-01-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0006_auto_20200106_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='room_readers', to='administracja.Room'),
            preserve_default=False,
        ),
    ]
