# Generated by Django 3.0.2 on 2020-01-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0007_reader_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('desc', models.CharField(max_length=50)),
                ('admin', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
