# Generated by Django 3.0.2 on 2020-01-12 12:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0008_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pesel', models.CharField(max_length=11)),
                ('hire_date', models.DateTimeField(default=datetime.datetime.now)),
                ('fire_date', models.DateTimeField(blank=True, null=True)),
                ('anonymized', models.BooleanField(default=False)),
                ('anonymization_date', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
