# Generated by Django 3.0.2 on 2020-01-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0009_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
