# Generated by Django 3.0.2 on 2020-01-12 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0010_person_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='anonymization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='fire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='hire_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='PersonRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracja.Person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracja.Role')),
            ],
        ),
    ]
