# Generated by Django 3.0.2 on 2020-01-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0011_auto_20200112_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='persons',
            field=models.ManyToManyField(blank=True, related_name='used_roles', through='administracja.PersonRoles', to='administracja.Person'),
        ),
    ]
