# Generated by Django 3.0.2 on 2020-01-12 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0012_role_persons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(max_length=48, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('HID', 'HID 13.56MHz 4kb'), ('Mifare', 'Mifare 13.56MHz 1kb'), ('Unique', 'Unique 125kHZ 1kb')], max_length=10)),
                ('supplier', models.CharField(max_length=100)),
                ('release_date', models.DateField(default=datetime.datetime.now)),
                ('valid_date', models.DateField(default=datetime.datetime.now)),
                ('active', models.BooleanField(default=False)),
                ('substitute', models.BooleanField(default=False)),
                ('main_card_id', models.CharField(blank=True, max_length=48)),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='administracja.Person')),
            ],
        ),
    ]
