# Generated by Django 3.0.2 on 2020-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0013_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('HID', 'HID'), ('Mifare', 'Mifare'), ('Unique', 'Unique')], max_length=10),
        ),
        migrations.AlterField(
            model_name='card',
            name='valid_date',
            field=models.DateField(blank=True, default=False),
        ),
    ]
