# Generated by Django 3.0.2 on 2020-01-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0014_auto_20200112_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='valid_date',
            field=models.DateField(blank=True),
        ),
    ]
