# Generated by Django 3.0.2 on 2020-01-12 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0015_auto_20200112_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
