# Generated by Django 3.0.2 on 2020-01-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0017_auto_20200112_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='valid_date',
        ),
    ]
