# Generated by Django 3.0.2 on 2020-01-26 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0020_auto_20200112_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Karta', 'verbose_name_plural': 'Karty'},
        ),
        migrations.AddField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=False, verbose_name='aktywna'),
        ),
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(max_length=48, primary_key=True, serialize=False, unique=True, verbose_name='Nr karty'),
        ),
        migrations.AlterField(
            model_name='card',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='data wydania'),
        ),
        migrations.AlterField(
            model_name='card',
            name='substitute',
            field=models.BooleanField(default=False, verbose_name='karta zastępcza'),
        ),
        migrations.AlterField(
            model_name='card',
            name='supplier',
            field=models.CharField(max_length=100, verbose_name='dostawca'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('HID', 'HID'), ('Mifare', 'Mifare'), ('Unique', 'Unique')], max_length=10, verbose_name='typ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='valid_date',
            field=models.DateField(blank=True, null=True, verbose_name='data ważności'),
        ),
    ]
