# Generated by Django 3.0.2 on 2020-01-26 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0021_auto_20200126_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Osoba', 'verbose_name_plural': 'Osoby'},
        ),
        migrations.AddField(
            model_name='person',
            name='retention',
            field=models.IntegerField(default=5, verbose_name='Okres retencji RODO'),
        ),
        migrations.AlterField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Aktywna'),
        ),
        migrations.AlterField(
            model_name='person',
            name='anonymization_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data anonimizacji'),
        ),
        migrations.AlterField(
            model_name='person',
            name='anonymized',
            field=models.BooleanField(default=False, verbose_name='Zanomizowana'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania rekordu'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zwolnienia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='hire_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Data zatrudnienia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Imię i nazwisko'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pesel',
            field=models.CharField(max_length=11, verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Data aktualizacji rekordu'),
        ),
    ]
