# Generated by Django 3.0.2 on 2020-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0022_auto_20200126_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='main_card_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='person',
        ),
        migrations.RemoveField(
            model_name='card',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='substitute',
        ),
        migrations.AlterField(
            model_name='card',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='data dodania'),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='data modyfikacji'),
        ),
    ]
