# Generated by Django 3.0.2 on 2020-01-27 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0023_auto_20200127_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True, verbose_name='aktywna'),
        ),
    ]
