# Generated by Django 3.0.2 on 2020-01-27 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0024_auto_20200127_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracja.Person', verbose_name='Użytkownik'),
        ),
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('0', 'Available'), ('1', 'Assigned'), ('2', 'Disabled'), ('3', 'Unknown')], default='0', help_text='Status karty', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fire_date',
            field=models.DateField(blank=True, help_text='Data zwolnienia nie może być wcześniejsza niż data zatrudnienia', null=True, verbose_name='Data zwolnienia'),
        ),
        migrations.AlterField(
            model_name='person',
            name='pesel',
            field=models.CharField(help_text='Podaj poprawny PESEL', max_length=11, verbose_name='PESEL'),
        ),
        migrations.AlterField(
            model_name='person',
            name='retention',
            field=models.IntegerField(default=5, help_text='Standardowy okres retencji wynosi 5 lat + dni do końca roku kalendarzowego', verbose_name='Okres retencji RODO'),
        ),
    ]
