# Generated by Django 3.0.2 on 2020-01-27 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0025_auto_20200127_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracja.Person', verbose_name='Użytkownik'),
        ),
    ]
