# Generated by Django 3.0.2 on 2020-01-29 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0026_auto_20200127_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('0', 'Available'), ('1', 'Assigned'), ('2', 'Disabled')], default='0', help_text='Status karty', max_length=1, verbose_name='Status'),
        ),
    ]
