# Generated by Django 3.0.2 on 2020-01-29 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracja', '0027_auto_20200129_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='anonymization_date',
            new_name='hash_date',
        ),
    ]
